const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require.resolve('../site/app.js'), 'utf8');
const html = fs.readFileSync(require.resolve('../site/index.html'), 'utf8');
const channels = ['personal_application', 'star_recommendation', 'exam_distribution', 'special_selection'];
const records = Array.from({ length: 101 }, (_, i) => ({ id: String(i), year: i % 2 ? 114 : 115, channelKey: channels[i % 4], schoolName: '測試大學', departmentName: `測試系${i}` }));
const buttons = channels.map(channel => ({ dataset: { compareChannelToggle: channel }, classList: { toggle() {} }, setAttribute(name, value) { this[name] = value; } }));
const grid = { innerHTML: '', querySelectorAll: () => [] };
const clear = {};
const state = { records, compare: [], compareFilters: { year: 'all', channels: [...channels] } };
let alerts = 0;
const context = { state, els: { compareGrid: grid, compareYearFilter: {}, compareResultCount: {} }, fmt: new Intl.NumberFormat('zh-Hant-TW'),
  document: { getElementById: () => clear, querySelectorAll: () => buttons }, window: { alert: () => alerts++ },
  renderTable() {}, updateDetailCompareButton() {}, highlightHtml: r => `標準${r.id}`, channelBadge: r => r.channelKey, specialAdmissionBadgeHtml: () => '（軍校）', escapeHtml: String, escapeAttr: String };
vm.createContext(context);
const names = ['toggleCompare', 'renderCompare', 'filteredCompareRecords', 'workbenchRecordRowHtml'];
vm.runInContext(names.map(name => source.match(new RegExp(`function ${name}\\([\\s\\S]*?\\n\\}`))[0]).join('\n'), context);
for (let i = 0; i < 100; i++) context.toggleCompare(String(i));
assert.equal(state.compare.length, 100);
assert.equal(context.filteredCompareRecords().length, 100);
assert.equal((grid.innerHTML.match(/<tr>/g) || []).length, 101); // Header + all 100 rows, no hidden cap.
assert.ok(context.els.compareResultCount.textContent.includes('100 / 100'));
context.toggleCompare('100');
assert.equal(state.compare.length, 100);
assert.equal(alerts, 1);
context.toggleCompare('0');
context.toggleCompare('100');
assert.equal(state.compare.length, 100);
assert.ok(state.compare.some(r => r.id === '100'));
state.compareFilters.year = '114';
context.renderCompare();
assert.equal(context.filteredCompareRecords().length, 50);
state.compareFilters.channels = ['star_recommendation'];
context.renderCompare();
assert.equal(context.filteredCompareRecords().length, 25);
assert.equal(buttons[0]['aria-pressed'], 'false');
assert.equal(buttons[1]['aria-pressed'], 'true');
state.compareFilters.channels = [];
context.renderCompare();
assert.equal(context.filteredCompareRecords().length, 0);
assert.equal(state.compare.length, 100);
assert.ok(grid.innerHTML.includes('尚未選取入學管道'));
state.compareFilters = { year: 'all', channels: [...channels] };
context.renderCompare();
assert.equal(context.filteredCompareRecords().length, 100);
const row = context.workbenchRecordRowHtml(records[0], true);
assert.ok(row.includes('標準0') && row.includes('（軍校）') && row.includes('data-detail="0"') && row.includes('data-remove-compare="0"'));
assert.ok(context.workbenchRecordRowHtml(records[0]).includes('data-compare="0"'));
assert.equal((html.match(/data-compare-channel-toggle=/g) || []).length, 4);
assert.ok(html.includes('id="compareYearFilter"'));
console.log('Compare list: 100-limit, 101st rejection, remove/re-add, year and all four channel filters, retained selections, shared workbench rows passed.');
